service:
  name: hexagonal-lambda

plugins:
  - serverless-webpack

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs10.x
  environment:
    ACCOUNT_TABLE: "accounts"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: "*"
package:
  individually: true

functions:
  addAccountHttp:
    handler: handlerHttp.handler
    events:
      - httpApi:
          method: POST
          path: /v1/accounts

resources:
  Resources:
    AccontsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.ACCOUNT_TABLE}
    NewSQSQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: new-accounts-queue-${opt:stage, self:provider.stage}
